
spring:
  datasource:
    url: jdbc:mysql://175.24.16.47:3306/spider-manage?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456@Fuyi.com
    driver-class-name: com.mysql.jdbc.Driver


#mybatis-plus日志打印配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #logic-delete-field: flag                                # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1                                    # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0                                # 逻辑未删除值(默认为 0)

# xxl-job
xxl:
  job:
    admin:
      addresses: http://localhost:8096/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    executor:
      address:
      appname: local-executor                        # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      ip:                                            # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 10001                                    # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath:                                       # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30                           # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
    accessToken: jin10                                   # 执行器通讯TOKEN [选填]：非空时启用；

server:
  port: 18888

